app:
  transaction:
    validity-timeout: 60000
    roundingScale: 2

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        consumers-per-queue: 2

logging:
  level:
    transaction: DEBUG
    org.springframework.web: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: rabbitmq

---
spring:
  config:
    activate:
      on-profile: test

logging:
  level:
    transaction: INFO
    org.springframework.web: INFO
