apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-init-scripts" (include "fullname" .) }}
  namespace: {{ .Release.Namespace }}
data:
  0_init.sql: |-
{{ .Files.Get "init.sql" | indent 4 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "fullname" .) }}
  namespace: {{ .Release.Namespace }}
data:
  rootPassword: {{ .Values.database.root.password | b64enc | quote }}