---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{.Release.Namespace}}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.database.port }}
  selector:
    app.kubernetes.io/name: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ template "fullname" . }}

{{- if .Values.database.nodePort.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-nodeport
  namespace: {{.Release.Namespace}}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
      nodePort: {{ .Values.database.nodePort.port }}
  selector:
    app.kubernetes.io/name: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ template "fullname" . }}
{{- end }}