spring:
  application:
    name: simple-bond-issuer
  main:
    banner-mode: "off"
  jmx:
    enabled: false
  jackson:
    default-property-inclusion: non_empty
    mapper:
      default_view_inclusion: true
  datasource:
    # persisted
    # url: jdbc:h2:~/bond-db
    # in memory
    url: jdbc:h2:mem:bond-db
    username: some_db_user
    password: some_db_password
    driverClassName: org.h2.Driver
    initialization-mode: always
    hikari:
      auto-commit: false # hibernate.connection.provider_disables_autocommit is auto configured to be true when this is false
  jpa:
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        connection:
          useUnicode: true
          CharSet: utf8mb4
          characterEncoding: utf8mb4
          collationServer: utf8mb4_unicode_ci
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          import_files: "db/V0001__create_bonds.sql,
                         db/V0002__create_history_for_bonds.sql"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# tomcat access logs redirected to console output
server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: true

logging:
  level:
    bond: DEBUG
    jdbc: WARN
    jdbc.sqltiming: INFO
    # ignore the integer type conversion warning log in swagger
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR

log4jdbc:
  dump:
    sql:
      addsemicolon: true
      maxlinelength: 0
    booleanastruefalse: true
  trim:
    sql:
      extrablanklines: false
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  sqltiming:
    error:
      threshold: 1000
    warn:
      threshold: 100

app:
  api:
    prefix: /api/v1

---
spring:
  config.activate.on-profile: docker
  rabbitmq.host: rabbitmq

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    bond: INFO
    jdbc.sqltiming: WARN
