---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "fullname" .) }}
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  # let k8s b64 encode when creating secret and b64 decode when injecting it
  basicAuthUser: {{ .Values.secret.basicAuth.user | quote }}
  basicAuthPassword: {{ .Values.secret.basicAuth.password | quote }}
  dbUser: {{ .Values.secret.db.user | quote }}
  dbPassword: {{ .Values.secret.db.password | quote }}
  apiKey: {{ .Values.secret.alphaVantageApiKey | quote }}
