---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.envVars.APP_PORT }}
  selector:
    app.kubernetes.io/name: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

{{- if .Values.nodePort.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-nodeport
  namespace: {{.Release.Namespace}}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.envVars.APP_PORT }}
      targetPort: {{ .Values.envVars.APP_PORT }}
      nodePort: {{ .Values.nodePort.port }}
  selector:
    app.kubernetes.io/name: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
