FROM amazoncorretto:17-alpine-jdk

EXPOSE 8080

RUN addgroup -S app-runner -g 3000 && \
    adduser -S app-runner -G app-runner --uid 3000 --home /home/app-runner --disabled-password
USER app-runner:app-runner

WORKDIR /home/app-runner
COPY artifact/clothing-service.jar ./clothing-service.jar
COPY artifact/jfr-monitoring-agent.jar ./jfr-monitoring-agent.jar

ENV JAVA_TOOL_OPTIONS="-XX:MaxRAMPercentage=80 -Djfr.enabled.clothing=true"
CMD ["java", "-javaagent:./jfr-monitoring-agent.jar", "-jar", "./clothing-service.jar"]