version: '3.6'

volumes:
  influxdb-storage:
  grafana-storage:

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbit
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 20s
      timeout: 20s
      retries: 3
  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=grafana_exposed_metrics
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
  grafana:
    image: grafana/grafana:7.5.5
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=root
