version: '3.6'

volumes:
  rabbitmq-storage:
  influxdb-storage:
  grafana-storage:

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbit
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 20s
      timeout: 20s
      retries: 3
    volumes:
      - rabbitmq-storage:/var/lib/rabbitmq
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=grafana_exposed_metrics
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.5
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=root
  transaction-processor:
    container_name: transaction-processor
    build:
      context: simple-transaction-processor
    image: transaction-processor:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8080:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
  bond-issuer:
    container_name: bond-issuer
    build:
      context: .
      dockerfile: Dockerfile_bond
    image: bond-issuer:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      INFLUX_HOST: "influxdb"
      INFLUX_PORT: "8086"
      INFLUX_USER: "root"
      INFLUX_PASS: "root"
    ports:
      - 8081:8081
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb:
        condition: service_started
  clothing-service:
    container_name: clothing-service
    build:
      context: .
      dockerfile: Dockerfile_clothing
    image: clothing-service:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      INFLUX_HOST: "influxdb"
      INFLUX_PORT: "8086"
      INFLUX_USER: "root"
      INFLUX_PASS: "root"
    ports:
      - 8082:8082
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb:
        condition: service_started