version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbit
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 20s
      timeout: 20s
      retries: 3
  bond-issuer:
    container_name: bond-issuer
    build:
      context: simple-bond-issuer
    image: bond-issuer:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8081:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
  transaction-processor:
    container_name: transaction-processor
    build:
      context: simple-transaction-processor
    image: transaction-processor:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8082:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
